/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package durablefurniturejavaproject.Common;

import durablefurniturejavaproject.Bussiness.ProductImage;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.beans.EventHandler;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;

/**
 *
 * @author Redmibook 14
 */
public class ProductGalleryJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProductGalleryJFrame
     */
    public ProductGalleryJFrame(int ProductId) throws SQLException, IOException {
        initComponents();
        this.setLocationRelativeTo(null);

        this.ProductId = ProductId;
        showProductImages();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(15);
    }
    private int ProductId;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(40, 81, 163));
        setName("Gallery"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1040, 640));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1040, 640));

        jPanel1.setBackground(new java.awt.Color(40, 80, 163));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 2000));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1996, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void showProductImages() {
        Thread th = new Thread() {
            public void run() {
                ProductImage PrdImg = new ProductImage();
                List<ProductImage> lsPrdImg = new ArrayList<ProductImage>();
                try {
                    lsPrdImg = PrdImg.getImagesByProductId(ProductId);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductGalleryJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                int X = 50;
                int Y = 60;
                int increaseVariableX = 240;
                int increaseVariableY = 200;
                for (ProductImage prdImg : lsPrdImg) {
                    JLabel lbl = new JLabel();
                    JButton buttonDel = new JButton();

                    buttonDel.setText("Delete");
                    buttonDel.setBounds(X + 55, Y + 156, 100, 26);
                    buttonDel.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            ProductImage PrdImgsub = new ProductImage();
                            PrdImgsub.setImg(prdImg.getImg());
                            try {
                                PrdImgsub.DeleteImageByName();
                            } catch (SQLException ex) {
                                Logger.getLogger(ProductGalleryJFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            File file = new File(System.getProperty("user.dir") + "/Images/Products/" + prdImg.getImg());
                            file.delete();
                            jPanel1.remove(buttonDel);
                            jPanel1.remove(lbl);
                            jPanel1.repaint();
                        }
                    });

                    lbl.setBounds(X, Y, 200, 150);
                    BufferedImage img;
                    try {
                        img = ImageIO.read(new File(System.getProperty("user.dir") + "/Images/Products/" + prdImg.getImg()));
                        Image dimg = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
                        lbl.setIcon(new ImageIcon(dimg));
                    } catch (IOException ex) {
                        Logger.getLogger(ProductGalleryJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    jPanel1.add(lbl);
                    jPanel1.add(buttonDel);

                    X += increaseVariableX;
                    if (X >= 850) {
                        X = 50;
                        Y += increaseVariableY;
                    }
                    jPanel1.repaint();
                }

            }

        };
        th.start();
    }

    private void Delete(JButton buttonDel, JLabel lbl) {

        jPanel1.remove(buttonDel);
        jPanel1.remove(lbl);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
